import { useEffect, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Controller, useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { ALLERGENS, dishSchema, type DishFormInput, type DishFormValues } from './dish-validation';

type Item = { id: string; name: string; categoryId: string; price: number; description?: string | null; imageUrl?: string | null; isActive: boolean; isHit?: boolean; costPriceByn?: number | null; weightGrams?: number | null; kitchenDepartment?: string | null; cookingTimeMinutes?: number | null; calories?: number | null; proteins?: number | string | null; fats?: number | string | null; carbs?: number | string | null; allergens?: string[]; posItemId?: string | null };
type Category = { id: string; name: string };
type Group = { id?: string; name: string; isRequired: boolean; minSelection: number; maxSelection: number | null; modifierOptions: { id?: string; name: string; extraPriceByn: number }[] };
const api = async (path: string, init?: RequestInit) => { const token = localStorage.getItem('accessToken'); const response = await fetch(`/api/v1/admin/${path}`, { ...init, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...init?.headers } }); if (!response.ok) throw new Error('Не удалось сохранить изменения'); return response.status === 204 ? null : response.json(); };
const empty: DishFormValues = { name: '', description: '', categoryId: '', price: '', costPrice: '', imageUrl: '', weightGrams: '', kitchenDepartment: 'HOT', cookingTimeMinutes: '', isActive: true, isHit: false, calories: '', proteins: '', fats: '', carbs: '', allergens: [], posItemId: '' };
const numeric = (value: unknown) => value == null ? '' : String(value);

export default function MenuPage() {
  const dialogRef = useRef<HTMLElement>(null);
  const returnFocusRef = useRef<HTMLElement | null>(null);
  const client = useQueryClient(); const [selected, setSelected] = useState<Item | null>(null); const [tab, setTab] = useState('Основное'); const [groups, setGroups] = useState<Group[]>([]); const [groupsLoading, setGroupsLoading] = useState(false); const [groupsLoadError, setGroupsLoadError] = useState(false); const [error, setError] = useState(''); const [modifierErrors, setModifierErrors] = useState<Record<string, string>>({}); const [uploadCount, setUploadCount] = useState(0); const [uploadError, setUploadError] = useState('');
  const items = useQuery({ queryKey: ['menu-items'], queryFn: () => api('menu/items') as Promise<Item[]> });
  const categories = useQuery({ queryKey: ['menu-categories'], queryFn: () => api('menu/categories') as Promise<Category[]> });
  const form = useForm<DishFormInput, unknown, DishFormValues>({ resolver: zodResolver(dishSchema), defaultValues: empty });
  useEffect(() => {
    if (!selected) return;
    const firstFocusable = dialogRef.current?.querySelector<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])');
    firstFocusable?.focus();
    return () => returnFocusRef.current?.focus();
  }, [selected]);
  const save = useMutation({
    mutationFn: async (values: DishFormValues) => {
      const payload = {
        name: values.name, description: values.description || null, categoryId: values.categoryId,
        price: Math.round(Number(values.price) * 100), imageUrl: values.imageUrl || null,
        isActive: values.isActive, isHit: values.isHit,
        costPriceByn: values.costPrice ? Number(values.costPrice) : null,
        weightGrams: values.weightGrams ? Number(values.weightGrams) : null,
        kitchenDepartment: values.kitchenDepartment,
        cookingTimeMinutes: values.cookingTimeMinutes ? Number(values.cookingTimeMinutes) : null,
        calories: values.calories ? Number(values.calories) : null,
        proteins: values.proteins ? Number(values.proteins) : null,
        fats: values.fats ? Number(values.fats) : null, carbs: values.carbs ? Number(values.carbs) : null,
        allergens: values.allergens, posItemId: values.posItemId || null,
      };
      let savedItem = selected!;
      if (savedItem.id === 'new') {
        savedItem = await api('menu/items', { method: 'POST', body: JSON.stringify({ name: values.name, categoryId: values.categoryId, price: Math.round(Number(values.price) * 100), description: values.description, imageUrl: values.imageUrl }) });
        setSelected(savedItem);
      }
      const persistedItem = await api(`menu/items/${savedItem.id}`, { method: 'PUT', body: JSON.stringify(payload) });
      savedItem = persistedItem ?? savedItem;
      for (const [groupIndex, group] of groups.entries()) {
        const saved = group.id
          ? await api(`menu/modifier-groups/${group.id}`, { method: 'PUT', body: JSON.stringify({ name: group.name, minSelected: group.minSelection, maxSelected: group.maxSelection, isRequired: group.isRequired }) })
          : await api(`menu/items/${savedItem.id}/modifier-groups`, { method: 'POST', body: JSON.stringify({ name: group.name, minSelected: group.minSelection, maxSelected: group.maxSelection, isRequired: group.isRequired }) });
        const groupId = group.id ?? saved.id;
        if (!group.id) setGroups((current) => current.map((entry, index) => index === groupIndex ? { ...entry, id: groupId } : entry));
        for (const [optionIndex, option] of group.modifierOptions.entries()) {
          if (option.id) await api(`menu/modifier-options/${option.id}`, { method: 'PUT', body: JSON.stringify({ name: option.name, extraPriceByn: option.extraPriceByn }) });
          else {
            const created = await api(`menu/modifier-groups/${groupId}/options`, { method: 'POST', body: JSON.stringify({ name: option.name, extraPriceByn: option.extraPriceByn }) });
            setGroups((current) => current.map((entry, index) => index === groupIndex ? { ...entry, modifierOptions: entry.modifierOptions.map((item, itemIndex) => itemIndex === optionIndex ? { ...item, id: created.id } : item) } : entry));
          }
        }
      }
    },
    onSuccess: async () => { await client.invalidateQueries({ queryKey: ['menu-items'] }); await client.invalidateQueries({ queryKey: ['guest-menu'] }); setSelected(null); },
  });
  const open = async (item: Item) => { returnFocusRef.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setSelected(item); setTab('Основное'); setError(''); setGroups([]); setGroupsLoading(true); setGroupsLoadError(false); form.reset({ ...empty, name: item.name, description: item.description ?? '', categoryId: item.categoryId, price: String(item.price / 100), imageUrl: item.imageUrl ?? '', isActive: item.isActive, isHit: item.isHit ?? false, costPrice: numeric(item.costPriceByn), weightGrams: numeric(item.weightGrams), kitchenDepartment: (item.kitchenDepartment as DishFormValues['kitchenDepartment']) || 'HOT', cookingTimeMinutes: numeric(item.cookingTimeMinutes), calories: numeric(item.calories), proteins: numeric(item.proteins), fats: numeric(item.fats), carbs: numeric(item.carbs), allergens: (item.allergens ?? []) as DishFormValues['allergens'], posItemId: item.posItemId ?? '' }); try { setGroups(await api(`menu/items/${item.id}/modifier-groups`)); } catch { setGroupsLoadError(true); } finally { setGroupsLoading(false); } };
  const upload = async (file?: File) => { if (!file) return; setUploadCount((count) => count + 1); setUploadError(''); try { const signed = await api('media/presign', { method: 'POST', body: JSON.stringify({ contentType: file.type }) }); const body = new FormData(); Object.entries(signed.uploadFields as Record<string,string>).forEach(([key, value]) => body.append(key, value)); body.append('file', file); const response = await fetch(signed.uploadUrl, { method: 'POST', body }); if (!response.ok) throw new Error('Не удалось загрузить фото'); form.setValue('imageUrl', signed.imageUrl); } catch { setUploadError('Не удалось загрузить фото. Повторите загрузку, прежде чем сохранять блюдо.'); } finally { setUploadCount((count) => count - 1); } };
  const validateGroups = () => {
    const next: Record<string, string> = {};
    groups.forEach((group, groupIndex) => {
      if (!group.name.trim()) next[`group-${groupIndex}`] = 'Укажите название группы';
      if (!Number.isInteger(group.minSelection) || group.minSelection < 0) next[`min-${groupIndex}`] = 'Укажите неотрицательное целое число';
      if (group.maxSelection !== null && (!Number.isInteger(group.maxSelection) || group.maxSelection < 0)) next[`max-${groupIndex}`] = 'Укажите неотрицательное целое число';
      if (group.maxSelection !== null && group.minSelection > group.maxSelection) next[`bounds-${groupIndex}`] = 'Минимальный выбор не может превышать максимальный';
      group.modifierOptions.forEach((option, optionIndex) => {
        if (!option.name.trim()) next[`option-${groupIndex}-${optionIndex}`] = 'Укажите название опции';
        if (!Number.isFinite(option.extraPriceByn) || option.extraPriceByn < 0) next[`price-${groupIndex}-${optionIndex}`] = 'Доплата должна быть неотрицательным числом';
      });
    });
    setModifierErrors(next);
    return Object.keys(next).length === 0;
  };
  const deleteGroup = async (index: number) => { const group = groups[index]; if (group.id) await api(`menu/modifier-groups/${group.id}`, { method: 'DELETE' }); setGroups((current) => current.filter((_, currentIndex) => currentIndex !== index)); };
  const deleteOption = async (groupIndex: number, optionIndex: number) => { const option = groups[groupIndex]?.modifierOptions[optionIndex]; if (option?.id) await api(`menu/modifier-options/${option.id}`, { method: 'DELETE' }); setGroups((current) => current.map((group, index) => index === groupIndex ? { ...group, modifierOptions: group.modifierOptions.filter((_, currentIndex) => currentIndex !== optionIndex) } : group)); };
  const addGroup = () => { setModifierErrors({}); setGroups((current) => [...current, { name: '', isRequired: false, minSelection: 0, maxSelection: null, modifierOptions: [] }]); };
  return <main className="min-h-svh bg-background p-8 text-on-background"><header className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Меню</h1><p className="text-sm opacity-60">Блюда ресторана</p></div><button className="rounded-lg bg-primary px-4 py-2 text-white" onClick={() => { returnFocusRef.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setSelected({ id: 'new', name: '', categoryId: '', price: 0, isActive: true }); setTab('Основное'); setGroups([]); setGroupsLoading(false); setGroupsLoadError(false); setError(''); form.reset(empty); }}>Добавить блюдо</button></header>{items.isLoading ? <p>Загрузка…</p> : items.isError ? <p role="alert">Не удалось загрузить меню</p> : <div className="overflow-hidden rounded-xl border border-on-background/10 bg-white"><table className="w-full text-left"><thead><tr className="border-b"><th className="p-4">Блюдо</th><th className="p-4">Категория</th><th className="p-4">Цена</th><th className="p-4">Статус</th><th /></tr></thead><tbody>{items.data?.map((item) => <tr key={item.id} className="border-b last:border-0"><td className="p-4">{item.name}</td><td className="p-4">{categories.data?.find((c) => c.id === item.categoryId)?.name ?? '—'}</td><td className="p-4">{(item.price / 100).toFixed(2)} BYN</td><td className="p-4">{item.isActive ? 'Активно' : 'Скрыто'}</td><td className="p-4 text-right"><button className="text-primary hover:underline" onClick={() => void open(item)}>Редактировать</button></td></tr>)}</tbody></table></div>}
  {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onMouseDown={(event) => { if (event.target === event.currentTarget) setSelected(null); }}><section ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="dish-title" className="dish-dialog max-h-[90vh] w-full max-w-4xl overflow-auto rounded-xl bg-background p-6 shadow-xl" onKeyDown={(event) => { if (event.key === 'Escape') { event.stopPropagation(); setSelected(null); } if (event.key === 'Tab') { const focusable = Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])')); const first = focusable[0]; const last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } }}><header className="mb-5 flex justify-between"><h2 id="dish-title" className="text-xl font-semibold">Редактирование блюда</h2><button aria-label="Закрыть" onClick={() => setSelected(null)}>✕</button></header><nav className="mb-5 flex gap-2 border-b">{['Основное','Модификаторы','Питание & Аллергены','POS'].map((name) => <button key={name} onClick={() => setTab(name)} className={`border-b-2 px-3 py-2 text-sm ${tab === name ? 'border-primary text-primary' : 'border-transparent'}`}>{name}</button>)}</nav>
  <form onSubmit={form.handleSubmit(async (values) => { setError(''); if (groupsLoadError || uploadCount > 0 || uploadError || !validateGroups()) return; try { await save.mutateAsync(values); } catch { setError('Не удалось сохранить блюдо. Проверьте данные и повторите попытку.'); } })}>
  {tab === 'Основное' && <div className="grid gap-4 md:grid-cols-2"><Field label="Название" error={form.formState.errors.name?.message}><input {...form.register('name')} /></Field><Field label="Категория" error={form.formState.errors.categoryId?.message}><select {...form.register('categoryId')}><option value="">Выберите категорию</option>{categories.data?.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Описание" className="md:col-span-2"><textarea {...form.register('description')} rows={3} /></Field><Field label="Цена, BYN" error={form.formState.errors.price?.message}><input type="number" min="0" step="0.01" required {...form.register('price')} /></Field><Field label="Себестоимость, BYN"><input type="number" step="0.01" {...form.register('costPrice')} /></Field><Field label="Граммовка, г"><input type="number" {...form.register('weightGrams')} /></Field><Field label="Цех"><select {...form.register('kitchenDepartment')}><option value="HOT">Горячий</option><option value="COLD">Холодный</option><option value="BAR">Бар</option></select></Field><Field label="Время приготовления, мин"><input type="number" {...form.register('cookingTimeMinutes')} /></Field><Field label="Фото"><label className="flex cursor-pointer items-center gap-3 rounded-lg border border-dashed p-3" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); void upload(event.dataTransfer.files[0]); }}><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => void upload(e.target.files?.[0])} />{form.watch('imageUrl') && <img src={form.watch('imageUrl')} alt="Фото блюда" className="h-12 w-12 rounded object-cover" />}</label>{uploadCount > 0 && <span role="status" className="block">Загрузка фото…</span>}{uploadError && <span role="alert" className="block text-red-600">{uploadError}</span>}</Field><div className="flex gap-5"><label><input type="checkbox" {...form.register('isActive')} /> Активно</label><label><input type="checkbox" {...form.register('isHit')} /> Хит</label></div></div>}
  {tab === 'Модификаторы' && <div className="space-y-4">{groupsLoading && <p>Загрузка групп модификаторов…</p>}{groupsLoadError && <p role="alert" className="text-red-600">Не удалось загрузить группы модификаторов. Повторите попытку, прежде чем сохранять блюдо.</p>}{!groupsLoading && !groupsLoadError && <>{groups.map((group, index) => <fieldset key={group.id ?? index} className="rounded-lg border p-4"><div className="grid gap-3 md:grid-cols-4"><Field label="Название группы" error={modifierErrors[`group-${index}`]}><input value={group.name} onChange={(e) => setGroups(groups.map((g,i) => i === index ? {...g,name:e.target.value} : g))} /></Field><label className="pt-7"><input type="checkbox" checked={group.isRequired} onChange={(e) => setGroups(groups.map((g,i) => i === index ? {...g,isRequired:e.target.checked} : g))} /> Обязательная</label><Field label="Мин. выбор" error={modifierErrors[`min-${index}`]}><input type="number" min="0" value={group.minSelection} onChange={(e) => setGroups(groups.map((g,i) => i === index ? {...g,minSelection:Number(e.target.value)} : g))} /></Field><Field label="Макс. выбор" error={modifierErrors[`max-${index}`] || modifierErrors[`bounds-${index}`]}><input type="number" min="0" value={group.maxSelection ?? ''} onChange={(e) => setGroups(groups.map((g,i) => i === index ? {...g,maxSelection:e.target.value ? Number(e.target.value) : null} : g))} /></Field></div>{group.modifierOptions.map((option, oi) => <div key={option.id ?? oi} className="mt-3 grid grid-cols-[1fr_150px_auto] gap-3"><Field label="Опция" error={modifierErrors[`option-${index}-${oi}`]}><input value={option.name} onChange={(e) => setGroups(groups.map((g,i) => i === index ? {...g,modifierOptions:g.modifierOptions.map((o,j) => j === oi ? {...o,name:e.target.value} : o)} : g))} /></Field><Field label="Доплата, BYN" error={modifierErrors[`price-${index}-${oi}`]}><input type="number" step="0.01" value={option.extraPriceByn} onChange={(e) => setGroups(groups.map((g,i) => i === index ? {...g,modifierOptions:g.modifierOptions.map((o,j) => j === oi ? {...o,extraPriceByn:Number(e.target.value)} : o)} : g))} /></Field><button type="button" aria-label="Удалить опцию" className="mt-6 text-red-600" onClick={() => void deleteOption(index, oi).catch(() => setError('Не удалось удалить опцию'))}>Удалить</button></div>)}<div className="mt-3 flex gap-4"><button type="button" className="text-primary" onClick={() => setGroups(groups.map((g,i) => i === index ? {...g,modifierOptions:[...g.modifierOptions,{name:'',extraPriceByn:0}]} : g))}>+ Добавить опцию</button><button type="button" className="text-red-600" onClick={() => void deleteGroup(index).catch(() => setError('Не удалось удалить группу'))}>Удалить группу</button></div></fieldset>)}<button type="button" className="text-primary" onClick={addGroup}>+ Добавить группу</button></>}</div>}
  {tab === 'Питание & Аллергены' && <div className="grid gap-4 md:grid-cols-2">{(['calories','proteins','fats','carbs'] as const).map((field) => <Field key={field} label={{calories:'Ккал',proteins:'Белки, г',fats:'Жиры, г',carbs:'Углеводы, г'}[field]}><input type="number" step={field === 'calories' ? '1' : '0.01'} {...form.register(field)} /></Field>)}<Field label="Аллергены" className="md:col-span-2"><Controller name="allergens" control={form.control} render={({field}) => <select multiple value={field.value} onChange={(e) => field.onChange(Array.from(e.target.selectedOptions, (o) => o.value))} className="h-52">{Object.entries(ALLERGENS).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select>} /></Field></div>}
  {tab === 'POS' && <Field label="Идентификатор позиции POS"><input {...form.register('posItemId')} placeholder="Введите pos_item_id" /></Field>}
  {error && <p role="alert" className="mt-4 text-sm text-red-600">{error}</p>}<footer className="mt-6 flex justify-end gap-3 border-t pt-4"><button type="button" className="rounded-lg border px-4 py-2" onClick={() => setSelected(null)}>Отмена</button><button type="submit" disabled={save.isPending || groupsLoading || groupsLoadError || uploadCount > 0 || Boolean(uploadError)} className="rounded-lg bg-primary px-4 py-2 text-white disabled:opacity-50">{save.isPending ? 'Сохранение…' : 'Сохранить'}</button></footer></form></section></div>}</main>;
}
function Field({label, error, className = '', children}: {label:string; error?:string; className?:string; children: React.ReactNode}) { return <label className={`block space-y-1 text-sm ${className}`}><span>{label}</span>{children}{error && <span className="block text-red-600">{error}</span>}</label>; }
