import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { changePlan, extendTrial, getOverview, setBlocked, type PlanType, type TenantStatus } from './superadmin.api';

const plans: { id: PlanType; title: string }[] = [{ id: 'TRIAL', title: 'Триал' }, { id: 'STARTER', title: 'Стартер' }, { id: 'PRO', title: 'Про' }, { id: 'ENTERPRISE', title: 'Энтерпрайз' }];
const statusNames: Record<TenantStatus, string> = { TRIAL: 'На триале', ACTIVE: 'Активен', BLOCKED: 'Заблокирован' };
const money = (value: number) => `${value.toLocaleString('ru-RU', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} BYN`;

export default function SuperadminPage() {
  const queryClient = useQueryClient();
  const [planFilter, setPlanFilter] = useState('ALL');
  const [statusFilter, setStatusFilter] = useState('ALL');
  const [trialTenant, setTrialTenant] = useState<string | null>(null);
  const [trialError, setTrialError] = useState('');
  const query = useQuery({ queryKey: ['superadmin', 'overview'], queryFn: getOverview });
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['superadmin', 'overview'] });
  const act = async (fn: () => Promise<unknown>) => { try { await fn(); refresh(); } catch { window.alert('Ошибка сервера. Попробуйте позже.'); } };
  const tenants = (query.data?.tenants ?? []).filter((tenant) => (planFilter === 'ALL' || tenant.plan === planFilter) && (statusFilter === 'ALL' || tenant.status === statusFilter));
  return <main className="min-h-svh bg-background p-6 text-on-background md:p-10"><div className="mx-auto max-w-7xl">
    <header><p className="text-sm text-on-background/60">Bonapp · Платформа</p><h1 className="mt-1 text-3xl font-semibold">Суперадмин</h1></header>
    {query.isPending && <p className="mt-8">Загружаем данные…</p>}{query.isError && <p role="alert" className="mt-8">Не удалось загрузить данные. Попробуйте позже.</p>}
    {query.data && <>
      <section aria-label="Метрики платформы" className="mt-8 grid gap-4 md:grid-cols-3">{[['Подписочная выручка за месяц', money(query.data.metrics.subscriptionRevenueByn)], ['Активные рестораны', query.data.metrics.activeRestaurants], ['QR-заказы сегодня', query.data.metrics.qrOrdersToday]].map(([label, value]) => <article key={label} className="rounded-2xl border border-outline-variant bg-surface-card p-6"><p className="text-sm text-on-background/60">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p></article>)}</section>
      <section className="mt-6 rounded-2xl border border-outline-variant bg-surface-card p-6"><h2 className="font-semibold">Подписочная выручка · 12 месяцев</h2><div className="mt-4 h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={query.data.growth}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip formatter={(value) => money(Number(value))}/><Area type="monotone" dataKey="subscriptionRevenueByn" name="Подписочная выручка, BYN" stroke="#e0533c" fill="#e0533c" fillOpacity={0.15}/></AreaChart></ResponsiveContainer></div></section>
      <section className="mt-8"><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-xl font-semibold">Тенанты</h2><div className="flex gap-3"><label className="text-sm">План <select aria-label="Фильтр по плану" value={planFilter} onChange={(event) => setPlanFilter(event.target.value)} className="ml-2 rounded-lg border bg-white p-2"><option value="ALL">Все</option>{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.title}</option>)}</select></label><label className="text-sm">Статус <select aria-label="Фильтр по статусу" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)} className="ml-2 rounded-lg border bg-white p-2"><option value="ALL">Все</option>{Object.entries(statusNames).map(([value, title]) => <option key={value} value={value}>{title}</option>)}</select></label></div></div>
      <div className="mt-4 overflow-x-auto rounded-xl border border-outline-variant bg-surface-card"><table className="w-full text-left text-sm"><thead><tr className="border-b border-outline-variant"><th className="p-4">Название</th><th className="p-4">План</th><th className="p-4">Триал до</th><th className="p-4">Выручка за 30 дней</th><th className="p-4">Статус</th><th className="p-4">Действия</th></tr></thead><tbody>{tenants.map((tenant) => <tr key={tenant.id} className="border-b border-outline-variant last:border-0"><td className="p-4 font-medium">{tenant.name}</td><td className="p-4">{plans.find((plan) => plan.id === tenant.plan)?.title}</td><td className="p-4">{tenant.trialEndsAt ? new Date(tenant.trialEndsAt).toLocaleDateString('ru-RU') : '—'}</td><td className="p-4">{money(tenant.revenue30dByn)}</td><td className="p-4">{statusNames[tenant.status]}</td><td className="p-4"><details><summary className="cursor-pointer text-primary">Действия</summary><div className="absolute z-10 grid gap-2 rounded-lg border bg-white p-3 shadow"><label className="text-xs">Изменить план<select aria-label={`План для ${tenant.name}`} value={tenant.plan} onChange={(event) => void act(() => changePlan(tenant.id, event.target.value as PlanType))} className="mt-1 block rounded border p-1">{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.title}</option>)}</select></label><button className="text-left text-primary" onClick={() => void act(() => setBlocked(tenant.id, tenant.status !== 'BLOCKED'))}>{tenant.status === 'BLOCKED' ? 'Разблокировать' : 'Заблокировать'}</button>{tenant.status === 'TRIAL' && <button className="text-left text-primary" onClick={() => { setTrialError(''); setTrialTenant(tenant.id); }}>Продлить триал на 30 дней</button>}</div></details></td></tr>)}</tbody></table>{tenants.length === 0 && <p className="p-6 text-center text-on-background/60">Нет тенантов по выбранным фильтрам</p>}</div></section>
      {trialTenant && (() => { const tenant = query.data.tenants.find((item) => item.id === trialTenant); const now = new Date(); const trialEnd = tenant?.trialEndsAt ? new Date(tenant.trialEndsAt) : null; const base = trialEnd && trialEnd > now ? trialEnd : now; const nextEnd = new Date(base.getTime() + 30 * 86400000); return <div className="fixed inset-0 z-20 flex items-center justify-center bg-black/40 p-4"><section role="dialog" aria-modal="true" aria-labelledby="trial-dialog-title" className="w-full max-w-md rounded-2xl bg-white p-6"><h2 id="trial-dialog-title" className="text-xl font-semibold">Продлить триал</h2><p className="mt-3">Продлить триал для {tenant?.name} на 30 дней?</p><p className="mt-2">Новая дата окончания: {nextEnd.toLocaleDateString('ru-RU')}</p>{trialError && <p role="alert" className="mt-3 text-error">{trialError}</p>}<div className="mt-6 flex justify-end gap-3"><button className="rounded-lg border px-4 py-2" onClick={() => setTrialTenant(null)}>Отмена</button><button className="rounded-lg bg-primary px-4 py-2 text-on-primary" onClick={() => void extendTrial(trialTenant).then(() => { setTrialTenant(null); refresh(); }).catch(() => setTrialError('Ошибка сервера. Попробуйте позже.'))}>Продлить</button></div></section></div>; })()}
    </>}
  </div></main>;
}
